/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:3b3a7b8d-6b55-4abf-bd7f-2b5254e1d348",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_k4Mj1YZmh",
    "aws_user_pools_web_client_id": "366397tnmpqdd5p5ntmegbu0f2",
    "oauth": {}
};


export default awsmobile;
